apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: pings.example.com
spec:
  group: example.com
  version: v1
  names:
    kind: Ping
    plural: pings
    singular: ping
  scope: Namespaced
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: pongs.example.com
spec:
  group: example.com
  version: v1
  names:
    kind: Pong
    plural: pongs
    singular: pong
  scope: Namespaced